services:
  stock-analysis-app:
    build: .
    ports:
      - "5001:5001" # Updated to use port 5001
    volumes:
      - ./data:/app/data # Mount a local folder for persistent storage
      - /home/puneeth/repo/stock_fundamental:/app # Mount the host directory to /app in the container
    restart: always
