global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "alerts@stockanalysis.com"
  smtp_auth_username: "${SMTP_USERNAME}"
  smtp_auth_password: "${SMTP_PASSWORD}"

templates:
  - "/etc/alertmanager/templates/*.tmpl"

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "email-alerts"
  routes:
    - match:
        severity: critical
      receiver: "email-alerts"
      continue: true
    - match:
        severity: warning
      receiver: "email-alerts"

receivers:
  - name: "email-alerts"
    email_configs:
      - to: "${ALERT_EMAIL}"
        subject: '{{ template "email.subject" . }}'
        body: '{{ template "email.body" . }}'
        headers:
          From: "Stock Analysis Platform <alerts@stockanalysis.com>"
          Subject: '{{ template "email.subject" . }}'

  - name: "slack-alerts"
    slack_configs:
      - api_url: "${SLACK_WEBHOOK_URL}"
        channel: "#alerts"
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]
