name: Template Smoke Tests

on:
  push:
    branches: [main, bmad-refactoring]
  pull_request:

jobs:
  template-smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run template smoke tests
        run: |
          python -m pytest -q tests/test_template_smoke.py

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: template-smoke-results
          path: tests
